import {NextResponse} from "next/server";
import {configuredEmailSettings,sendResendEmail} from "../../../../lib/resend";
import {envReady,score360,integrated360Html} from "../../../../lib/360";

async function sb(path:string,init:RequestInit={}){
  const res=await fetch(`${process.env.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:process.env.SUPABASE_SECRET_KEY!,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})},cache:"no-store"});
  const text=await res.text(); if(!res.ok) throw new Error(text); return text?JSON.parse(text):null;
}

export async function GET(req:Request){
  try{if(!envReady())return NextResponse.json({error:"360 review storage is not configured."},{status:503});const token=new URL(req.url).searchParams.get("token");if(!token)return NextResponse.json({error:"Missing review token."},{status:400});const reviewers=await sb(`pc_360_reviewers?select=id,session_id,reviewer_email,completed_at&token=eq.${encodeURIComponent(token)}`);if(!reviewers?.length)return NextResponse.json({error:"This review link is invalid or has expired."},{status:404});const sessions=await sb(`pc_360_sessions?select=participant_name,inviter_name,invitation_message&id=eq.${reviewers[0].session_id}`);if(!sessions?.length)return NextResponse.json({error:"Review session not found."},{status:404});return NextResponse.json({participantName:sessions[0].participant_name,inviterName:sessions[0].inviter_name,completed:Boolean(reviewers[0].completed_at)});}catch(e){console.error(e);return NextResponse.json({error:"We couldn't load this review."},{status:500});}
}

export async function POST(req:Request){
  try{if(!envReady())return NextResponse.json({error:"360 review storage is not configured."},{status:503});const body=await req.json();const token=String(body.token||"");const reviewerName=String(body.reviewerName||"").trim();const answers=Array.isArray(body.answers)?body.answers.map(Number):[];if(!token||!reviewerName||answers.length!==18||answers.some((n:number)=>!Number.isInteger(n)||n<1||n>5))return NextResponse.json({error:"Please complete all 18 review questions."},{status:400});const rows=await sb(`pc_360_reviewers?select=id,session_id,completed_at&token=eq.${encodeURIComponent(token)}`);if(!rows?.length)return NextResponse.json({error:"This review link is invalid or has expired."},{status:404});const reviewer=rows[0];if(reviewer.completed_at)return NextResponse.json({error:"This review has already been submitted."},{status:409});await sb(`pc_360_reviewers?id=eq.${reviewer.id}`,{method:"PATCH",body:JSON.stringify({reviewer_name:reviewerName,answers,completed_at:new Date().toISOString()})});const sessions=await sb(`pc_360_sessions?select=id,participant_name,participant_email,self_answers&id=eq.${reviewer.session_id}`);const session=sessions[0];const all=await sb(`pc_360_reviewers?select=answers,completed_at&session_id=eq.${reviewer.session_id}`);const completed=all.filter((r:any)=>Array.isArray(r.answers)&&r.completed_at);if(completed.length===all.length){const scores=score360(session.self_answers,completed.map((r:any)=>r.answers));const html=integrated360Html(session.participant_name,scores,completed.length);const mail=await sendResendEmail({from:configuredEmailSettings().from,to:[session.participant_email],subject:`Your People Compound Integrated 360 Leadership Report`,html});if(!mail.ok)return NextResponse.json({ok:true,completed:completed.length,total:all.length,reportDelivery:"pending",message:"Your review was recorded. All reviewers are complete, but the integrated report email could not be sent."});return NextResponse.json({ok:true,completed:completed.length,total:all.length,reportDelivery:"sent"});}return NextResponse.json({ok:true,completed:completed.length,total:all.length,reportDelivery:"waiting"});}catch(e){console.error("360 review error",e);return NextResponse.json({error:"We couldn't save this review. Please try again."},{status:500});}
}
