import Image from "next/image";
import Link from "next/link";

export default function Page(){return <main>
<section className="pagehero"><div className="container"><div className="kicker">About People Compound</div><h1>People strategy for the moments when people capability becomes business capability.</h1><p className="lead">People Compound helps growing organizations build the systems, leadership and organizational capability required for what’s next.</p></div></section>
<section className="section"><div className="container grid2"><div><div className="kicker">Why People Compound</div><h2>People capability compounds over time.</h2><p className="lead">The quality of your hiring, leadership, operating systems, decision-making and culture shapes what your organization can execute next.</p><p>We bring strategic HR leadership, organizational development and coaching together to help leaders build capability that lasts beyond a single hire, initiative or moment of growth.</p></div><div className="card"><div className="checklist"><div className="check"><b>Build</b><span>Establish the foundation and systems.</span></div><div className="check"><b>Scale</b><span>Strengthen capability, leadership and organization.</span></div><div className="check"><b>Transform</b><span>Navigate change, integration and new growth.</span></div></div></div></div></section>
<section className="section section-sage"><div className="container"><div className="stats"><div className="stat"><strong>15+</strong><span>Years HR experience</span></div><div className="stat"><strong>120+</strong><span>Headcount scaled</span></div><div className="stat"><strong>40+</strong><span>Senior leaders recruited</span></div><div className="stat"><strong>$2M+</strong><span>Recruiting cost savings</span></div><div className="stat"><strong>ICF-PCC</strong><span>Coach training</span></div></div></div></section>
<section className="section page-image-section"><div className="container"><div className="page-image-frame about-page-image"><Image src="/images/about.webp" alt="People collaborating across an organization" fill sizes="(max-width: 900px) 100vw, 1180px" /></div></div></section>
<section className="section"><div className="container about-person-grid"><div><div className="kicker">The person behind People Compound</div><h2>Strategic HR leadership, grounded in building.</h2><div className="about-headshot"><Image src="/images/helen-sun.webp" alt="Helen Sun, founder of People Compound" width={500} height={500} sizes="(max-width: 900px) 100vw, 500px" /></div><a className="linkedin-profile" href="https://www.linkedin.com/in/helensun1/" target="_blank" rel="noopener noreferrer" aria-label="Helen Sun on LinkedIn"><span className="linkedin-icon">in</span><span>Connect with Helen on LinkedIn ↗</span></a></div><div><p>People Compound was founded by Helen Sun, an HR leader with experience across global biopharma, biotech and high-growth organizations. Her work has included building HR functions from the ground up, scaling teams, recruiting senior leaders, designing people systems, supporting transformation and coaching leaders through change.</p><p>The approach is practical by design: connect people strategy to the business, build the systems that make good intentions executable, and develop leaders who can carry the organization forward.</p><div className="card about-point-of-view"><div className="kicker">Our point of view</div><h3>People strategy should make the next stage possible.</h3><p>Not more process for the sake of process. Not HR disconnected from the business. The goal is an organization with the clarity, capability and leadership to execute what comes next.</p></div></div></div></section>
<section className="section section-dark"><div className="container cta"><div><div className="kicker">A question worth asking</div><h2>What becomes possible when your people capability compounds?</h2><p className="lead">The next stage of your organization starts with the capability you build today.</p></div><Link className="btn btn-gold" href="/contact">Start the conversation</Link></div></section>
</main>}