"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {buildReport} from "../../../lib/assessmentReports";
const questions=[
["Strategy","Our people strategy is clearly connected to our business strategy."],["Strategy","We have a clear view of the capabilities and talent we will need for our next stage of growth."],["Strategy","Our workforce and hiring priorities are driven by business needs rather than primarily by immediate vacancies."],
["Leadership","Our leaders communicate a clear direction and create alignment around priorities."],["Leadership","Our leaders have the capabilities needed for the organization's current stage of growth."],["Leadership","Our leaders consistently model the behaviors and culture we expect from others."],
["Organization","Roles, responsibilities, and decision rights are clear across the organization."],["Organization","Our organizational structure supports effective execution."],["Organization","People know who owns important decisions and how issues should be escalated."],
["Talent","We consistently attract candidates with the capabilities our business needs."],["Talent","Our hiring process gives us confidence that we are selecting the right people."],["Talent","We know which roles and capabilities are most critical to our future success."],
["Performance","Employees understand what is expected of them and how their work contributes to business priorities."],["Performance","Managers regularly provide useful feedback and address performance issues."],["Performance","Our performance management process helps improve performance rather than simply documenting it."],
["Culture","Our stated values are reflected in how decisions are actually made."],["Culture","Employees understand which behaviors are expected, encouraged, and reinforced."],["Culture","People can raise concerns and challenge ideas constructively."],
["Rewards","Our compensation philosophy supports our business and talent strategy."],["Rewards","Employees understand how performance, pay, and career progression are connected."],["Rewards","Our compensation and benefits practices are appropriate for the talent we need to attract and retain."],
["Development","Employees have meaningful opportunities to develop capabilities needed for their current and future roles."],["Development","Managers actively support the development of their people."],["Development","We have a clear approach for identifying and developing future leaders and critical talent."],
["HR Operations","Our HR policies, processes, and systems are reliable and scalable for our current stage."],["HR Operations","Managers have the guidance and tools they need to handle people-related decisions effectively."],["HR Operations","Our people data and HR processes provide leaders with useful information for decision-making."]];
const scale=["Not in place","Emerging / inconsistent","Functional","Strong","Well established"];
export default function Page(){const[a,setA]=useState<number[]>(Array(27).fill(0));const[done,setDone]=useState(false);const[report,setReport]=useState<any>(null);const[email,setEmail]=useState("");const[busy,setBusy]=useState(false);const[err,setErr]=useState("");const progress=useMemo(()=>a.filter(Boolean).length,[a]);
if(done&&report)return <main><section className="pagehero"><div className="container"><div className="kicker">Your organizational profile</div><h1>See where your organizational capability is strongest—and where to focus next.</h1><p className="lead">Use this profile as a practical starting point for reflection, development, and conversation.</p></div></section><section className="section"><div className="container"><div className="score-grid">{report.scores.map((x:any)=><div className="score-card" key={x.name}><span>{x.name}</span><strong>{x.score}</strong><div className="score-bar"><i style={{width:`${x.score/5*100}%`}}/></div></div>)}</div><div className="grid2 result-bottom"><div className="card"><div className="kicker">Strengths to leverage</div><h2>What is already working</h2><p>{report.strengths.map((x:any)=>`${x.name} (${x.score}/5)`).join(" · ")}</p></div><div className="card"><div className="kicker">Focus</div><h2>Where to practice next</h2>{report.recommendations.map((x:any)=><div className="result-item" key={x.name}><b>{x.name}</b><p>{x.text}</p></div>)}</div></div><div className="card report-card"><div className="kicker">Your 90-day action plan</div><h2>Focus → Build → Measure</h2>{report.actionPlan.map((x:any)=><div className="plan" key={x.name}><h3>{x.name}</h3><p><b>First 30 days:</b> {x.days30}</p><p><b>Days 31–60:</b> {x.days60}</p><p><b>Days 61–90:</b> {x.days90}</p></div>)}<p className="small-note">This is a development reflection tool, not a clinical or psychometric diagnosis.</p></div><div className="card email-card"><h2>Want the detailed report?</h2><p>We’ll send your profile and 90-day action plan to your inbox.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setErr("");try{const r=await fetch("/api/assessments/report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"organization-health",answers:a,email})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Please try again.");setErr("Report sent. Check your inbox.");}catch(e:any){setErr(e.message)}finally{setBusy(false)}}}><input type="email" required placeholder="Work email" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn btn-primary" disabled={busy}>{busy?"Sending…":"Email my report"}</button></form>{err&&<div className="notice">{err}</div>}</div><div className="actions"><Link className="btn btn-primary" href="/contact">Discuss your results</Link><Link className="btn btn-outline" href="/solutions">Explore Solutions</Link></div></div></section></main>;
return <main><section className="pagehero"><div className="container"><div className="kicker">Organizational Health Check</div><h1>Understand what your organization needs next.</h1><p className="lead">27 questions across nine organizational dimensions. There are no right or wrong answers. Answer based on your organization's current reality, not where you want it to be.</p><div className="assessment-start-meta"><b>27 questions</b><b>7–10 minutes</b><b>1–5 scale</b><b>Instant results</b></div></div></section><section className="section"><div className="container assessment-shell"><div className="assessment-progress"><span>{progress} of 27 answered</span><span>{Math.round(progress/27*100)}%</span></div>{questions.map((q,i)=><div className="question card" key={i}><div className="question-num">{String(i+1).padStart(2,"0")}</div><div><div className="tag">{q[0]}</div><h3>{q[1]}</h3><div className="scale">{scale.map((s,j)=><button key={s} className={a[i]===j+1?"selected":""} onClick={()=>setA(v=>{const n=[...v];n[i]=j+1;return n})}><strong>{j+1}</strong><span>{s}</span></button>)}</div></div></div>)}<div className="assessment-submit"><p className="small-note">Your initial results appear here without requiring an email.</p><button className="btn btn-primary" disabled={progress<27} onClick={()=>{setReport(buildReport("organization-health",a));setDone(true);window.scrollTo({top:0,behavior:"smooth"})}}>See my results →</button></div></div></section></main>}
