"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {buildReport} from "../../../lib/assessmentReports";
const questions=[
["Build Relationships","I intentionally build and maintain productive relationships with people across my organization."],["Build Relationships","I invest in relationships even when there is no immediate task or business need."],["Develop People","I regularly coach people on their development and give them opportunities to stretch."],["Develop People","I adapt my approach to help different people learn, grow, and become more independent."],["Deal with Ambiguity","I remain effective when priorities, requirements, or information are unclear or changing."],["Deal with Ambiguity","When I don't have all the information I need, I make reasonable assumptions, communicate them, and move forward."],["Lead Change","I actively communicate the purpose, impact, and direction of changes I lead."],["Lead Change","When people resist a change, I seek to understand their concerns and address them rather than simply pushing harder."],["Inspire Others","I connect people's day-to-day work to a larger purpose or goal."],["Inspire Others","I create enthusiasm and commitment around important goals, especially when the work is difficult."],["Think Critically & Strategically","I consider how decisions in my area will affect other functions and the organization as a whole."],["Think Critically & Strategically","Before making important decisions, I consider longer-term consequences, trade-offs, and second-order effects."],["Communicate Clearly","I communicate complex ideas in a way that is clear and easy for others to understand."],["Communicate Clearly","I adjust my message, level of detail, and communication style for different audiences."],["Create Accountability","I set clear expectations about responsibilities, priorities, and results."],["Create Accountability","I address missed commitments or performance concerns directly and constructively."],["Active Listening","I listen to understand another person's perspective before explaining or defending my own."],["Active Listening","When someone disagrees with me, I ask questions and explore their perspective before responding."]];
const scale=["Rarely","Sometimes","Often","Consistently","Very consistently"];
export default function Page(){const[a,setA]=useState<number[]>(Array(18).fill(0));const[done,setDone]=useState(false);const[report,setReport]=useState<any>(null);const[email,setEmail]=useState("");const[busy,setBusy]=useState(false);const[err,setErr]=useState("");const[show360,setShow360]=useState(false);const[inviterName,setInviterName]=useState("");const[participantName,setParticipantName]=useState("");const[participantEmail,setParticipantEmail]=useState("");const[reviewerEmails,setReviewerEmails]=useState(["","",""]);const[invitationMessage,setInvitationMessage]=useState("{{INVITER_NAME}} is inviting you to conduct a 360 review of {{PARTICIPANT_NAME}}. Your feedback will help assess their leadership behaviors and will be combined with the participant's self-assessment and other reviewer responses to generate an integrated report with gap analysis when all invited reviewers have completed the review.\n\nThank you for sharing candid, behavior-based feedback.");const[inviteStatus,setInviteStatus]=useState("");const progress=useMemo(()=>a.filter(Boolean).length,[a]);
if(done&&report)return <main><section className="pagehero"><div className="container"><div className="kicker">Your leadership profile</div><h1>See where your leadership capability is strongest—and where to focus next.</h1><p className="lead">Use this profile as a practical starting point for reflection, development, and conversation.</p></div></section><section className="section"><div className="container"><div className="score-grid">{report.scores.map((x:any)=><div className="score-card" key={x.name}><span>{x.name}</span><strong>{x.score}</strong><div className="score-bar"><i style={{width:`${x.score/5*100}%`}}/></div></div>)}</div><div className="grid2 result-bottom"><div className="card"><div className="kicker">Strengths to leverage</div><h2>What is already working</h2><p>{report.strengths.map((x:any)=>`${x.name} (${x.score}/5)`).join(" · ")}</p></div><div className="card"><div className="kicker">Focus</div><h2>Where to practice next</h2>{report.recommendations.map((x:any)=><div className="result-item" key={x.name}><b>{x.name}</b><p>{x.text}</p></div>)}</div></div><div className="card report-card"><div className="kicker">Your 90-day action plan</div><h2>Awareness → Practice → Feedback → Reflection</h2>{report.actionPlan.map((x:any)=><div className="plan" key={x.name}><h3>{x.name}</h3><p><b>First 30 days:</b> {x.days30}</p><p><b>Days 31–60:</b> {x.days60}</p><p><b>Days 61–90:</b> {x.days90}</p></div>)}<p className="small-note">This is a development reflection tool, not a clinical or psychometric diagnosis.</p></div><div className="card email-card"><h2>Want the detailed report?</h2><p>We’ll send your profile and 90-day action plan to your inbox.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setErr("");try{const r=await fetch("/api/assessments/report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"leadership",answers:a,email})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Please try again.");setErr("Report sent. Check your inbox.");}catch(e:any){setErr(e.message)}finally{setBusy(false)}}}><input type="email" required placeholder="Work email" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn btn-primary" disabled={busy}>{busy?"Sending…":"Email my report"}</button></form>{err&&<div className="notice">{err}</div>}</div><div className="card leadership-360-card">
<h2>Go beyond self-assessment: add a 360 review.</h2>
<p>Invite up to 3 people to assess the participant's leadership behaviors. When all invited reviewers complete their review, People Compound will generate an integrated report comparing self and observer perspectives with gap analysis.</p>
<button className="btn btn-outline" type="button" onClick={()=>setShow360(v=>!v)}>{show360?"Close 360 setup":"Set up a 360 review →"}</button>
{show360&&<form className="leadership-360-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setInviteStatus("");try{const r=await fetch("/api/360/invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inviterName,participantName,participantEmail,selfAnswers:a,reviewerEmails,invitationMessage})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Please try again.");setInviteStatus(`360 review created and ${j.invited} invitation${j.invited===1?"":"s"} sent.`);}catch(e:any){setInviteStatus(e.message)}finally{setBusy(false)}}}>
<label>Your name<br/><input required value={inviterName} onChange={e=>setInviterName(e.target.value)} placeholder="Your name"/></label>
<label>Participant name<br/><input required value={participantName} onChange={e=>setParticipantName(e.target.value)} placeholder="Person being reviewed"/></label>
<label>Participant email<br/><input required type="email" value={participantEmail} onChange={e=>setParticipantEmail(e.target.value)} placeholder="participant@company.com"/></label>
<div className="grid3"><label>Reviewer email 1<br/><input required type="email" value={reviewerEmails[0]} onChange={e=>setReviewerEmails(v=>[e.target.value,v[1],v[2]])} /></label><label>Reviewer email 2 (optional)<br/><input type="email" value={reviewerEmails[1]} onChange={e=>setReviewerEmails(v=>[v[0],e.target.value,v[2]])} /></label><label>Reviewer email 3 (optional)<br/><input type="email" value={reviewerEmails[2]} onChange={e=>setReviewerEmails(v=>[v[0],v[1],e.target.value])} /></label></div>
<label>Invitation message — editable<br/><textarea rows={8} value={invitationMessage} onChange={e=>setInvitationMessage(e.target.value)} /></label>
<p className="small-note">Use <code>{"{{INVITER_NAME}}"}</code> and <code>{"{{PARTICIPANT_NAME}}"}</code> as placeholders. Reviewers receive a unique link and complete the same 18 behavior-based questions.</p>
<button className="btn btn-primary" disabled={busy}>{busy?"Sending invitations…":"Send 360 invitations →"}</button>
{inviteStatus&&<div className={inviteStatus.startsWith("360 review created")?"notice":"notice notice-error"}>{inviteStatus}</div>}
</form>}
</div>
<div className="actions"><Link className="btn btn-primary" href="/contact">Discuss your results</Link><Link className="btn btn-outline" href="/leadership">Explore Leadership Development</Link></div></div></section></main>;
return <main><section className="pagehero"><div className="container"><div className="kicker">Leadership Assessment</div><h1>Understand how you lead today.</h1><p className="lead">18 behavior-based questions across nine leadership capabilities. There are no right or wrong answers—respond based on how you typically behave today.</p><div className="assessment-start-meta"><b>18 questions</b><b>5–7 minutes</b><b>1–5 scale</b><b>Instant results</b></div></div></section><section className="section"><div className="container assessment-shell"><div className="assessment-progress"><span>{progress} of 18 answered</span><span>{Math.round(progress/18*100)}%</span></div>{questions.map((q,i)=><div className="question card" key={i}><div className="question-num">{String(i+1).padStart(2,"0")}</div><div><div className="tag">{q[0]}</div><h3>{q[1]}</h3><div className="scale">{scale.map((s,j)=><button key={s} className={a[i]===j+1?"selected":""} onClick={()=>setA(v=>{const n=[...v];n[i]=j+1;return n})}><strong>{j+1}</strong><span>{s}</span></button>)}</div></div></div>)}<div className="assessment-submit"><p className="small-note">Your initial results appear here without requiring an email.</p><button className="btn btn-primary" disabled={progress<18} onClick={()=>{setReport(buildReport("leadership",a));setDone(true);window.scrollTo({top:0,behavior:"smooth"})}}>See my results →</button></div></div></section></main>}
