import Link from "next/link";
import type { Metadata } from "next";

const posts: Record<string, {category:string,title:string,description:string,read:string,sections:{heading:string,body:string[]}[]}> = {
  "people-strategy-for-whats-next": {category:"People Strategy",title:"People Strategy for What's Next: What Changes as Your Company Grows",description:"A practical framework for connecting business strategy, workforce planning, leadership, talent and HR infrastructure to the next stage of growth.",read:"8 min read",sections:[
    {heading:"People strategy should follow the business",body:["People strategy becomes useful when it answers a business question: what capabilities, leadership, organization and talent will we need to execute the next stage of the plan?","The people agenda should change as the company changes. The priorities of a 20-person company are not the same as those of a 150-person organization preparing for its next major milestone."]},
    {heading:"Five questions to ask",body:["1. What is the business trying to accomplish next?","2. Which capabilities are critical to that plan?","3. Where are the current organization and talent gaps?","4. Which systems or leadership behaviors will become constraints as we grow?","5. What needs to be built now so the organization is ready when the business needs it?"]},
    {heading:"Build the capability, not just the program",body:["A hiring plan without a repeatable talent process can create inconsistent quality. A performance process without manager capability can become administrative. Values without reinforcement in decisions, rewards and leadership behavior rarely become culture.","The stronger approach is to connect the pieces: strategy → organization → talent → leadership → systems → employee experience → measurement."]},
    {heading:"A practical next step",body:["Start by identifying the organization's current strengths and constraints. Then choose the few capabilities that matter most for the next stage rather than trying to improve everything at once.","The People Compound Organizational Health Check is designed as a starting point for that conversation."]}
  ]},
  "stop-rolling-the-dice-on-quality-of-hire": {category:"Talent Acquisition",title:"Stop Rolling the Dice on Quality of Hire",description:"A repeatable talent acquisition system connects role clarity, sourcing, assessment, closing, onboarding and quality-of-hire data.",read:"7 min read",sections:[{heading:"Hiring is a system",body:["Quality of hire is influenced long before an interview. It starts with understanding the business need, defining success and deciding what evidence will demonstrate capability."]},{heading:"The full talent acquisition chain",body:["Strategy → Attract → Source → Assess → Select → Close → Onboard → Measure → Improve","Each stage creates inputs for the next. Weak role definition makes assessment harder. Weak assessment makes selection less reliable. Weak onboarding makes it harder to distinguish hiring quality from integration problems."]},{heading:"Measure what happens after the offer",body:["A mature talent acquisition capability looks beyond time-to-fill. It can examine quality of hire, retention, hiring-manager satisfaction, source effectiveness, candidate experience and onboarding outcomes."]}]},
  "when-hr-needs-to-scale": {category:"HR Strategy",title:"When Does HR Need to Scale With the Business?",description:"The signals that your people infrastructure, manager capability and operating model are becoming constraints on growth.",read:"6 min read",sections:[{heading:"The trigger is not headcount alone",body:["HR complexity often increases because the business is changing: new geographies, new leaders, rapid hiring, commercialization, M&A, new compliance requirements or a shift in operating model."]},{heading:"Common signals",body:["Managers are improvising people decisions. Hiring quality varies by function. Policies live in scattered documents. Compensation decisions feel inconsistent. Leaders lack useful people data. Employee issues consume disproportionate leadership time."]},{heading:"Scale the system to the business",body:["The goal is not to create bureaucracy. It is to build enough structure that leaders can make consistent decisions while keeping the organization responsive."]}]},
  "from-founder-led-to-leader-led": {category:"Leadership",title:"From Founder-Led to Leader-Led: Building Management Capability",description:"How organizations can move from heroic individual leadership toward clear accountability, stronger managers and scalable decision-making.",read:"8 min read",sections:[{heading:"Growth changes the leadership job",body:["As organizations grow, founders and senior leaders cannot remain the primary source of context, decisions and problem-solving. The organization needs more leaders who can create clarity and accountability without constant escalation."]},{heading:"Build management capability deliberately",body:["Focus on clear expectations, feedback, delegation, decision rights, coaching and cross-functional relationships. Leadership development should be connected to real work rather than separated from it."]},{heading:"Use practice, not just training",body:["Awareness → Practice → Feedback → Reflection → Awareness. The cycle creates opportunities to apply new behaviors, learn from results and continue developing."]}]},
  "culture-is-a-system": {category:"Culture",title:"Culture Is a System, Not a Poster",description:"Values become culture when they shape decisions, behaviors, incentives, meetings and the everyday employee experience.",read:"6 min read",sections:[{heading:"The gap between stated and experienced culture",body:["Employees experience culture through what leaders reward, tolerate, prioritize and model—not only through stated values."]},{heading:"Make culture observable",body:["Translate values into behaviors. Then reinforce those behaviors through hiring, onboarding, performance, promotion, recognition, meetings and decision-making."]},{heading:"Measure the pattern",body:["Culture work becomes more useful when leaders can identify where stated expectations and everyday experience diverge, then choose specific behaviors and systems to address."]}]},
  "the-people-operating-system": {category:"HR Infrastructure",title:"The People Operating System: What Growing Companies Actually Need",description:"A practical view of the policies, processes, systems and governance that make people operations scalable without unnecessary bureaucracy.",read:"9 min read",sections:[{heading:"Infrastructure should create leverage",body:["A people operating system gives employees and managers reliable ways to navigate hiring, onboarding, performance, compensation, employee relations, development and offboarding."]},{heading:"Build the essentials first",body:["Start with the policies, decision rights, HR technology, data, manager guidance and core processes that the organization actually needs today. Design them so they can evolve with the next stage."]},{heading:"The test is usability",body:["A process is working when managers know what to do, employees know what to expect, leaders can see useful data and HR can operate consistently without unnecessary manual work."]}]},
  "leadership-capability-compounds": {category:"Leadership Development",title:"Leadership Capability Compounds",description:"Why leadership development works best as an ongoing cycle of awareness, practice, feedback, reflection and application.",read:"7 min read",sections:[{heading:"Development is behavior change",body:["Knowing a leadership concept is different from using it under pressure. Development becomes durable when leaders repeatedly practice new behaviors in real situations."]},{heading:"The development flywheel",body:["Awareness → Practice → Feedback → Reflection → Awareness. Each cycle gives the leader more information about what is working and what needs adjustment."]},{heading:"Start with a clear profile",body:["A structured leadership assessment can create a shared language for development across capabilities such as active listening, developing people, strategic thinking, accountability and leading change."]}]}
};

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://peoplecompound.com";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const post = posts[slug];
  if (!post) return { title: "Insight not found" };
  const url = `${siteUrl}/insights/${slug}`;
  return {
    title: post.title,
    description: post.description,
    alternates: { canonical: url },
    openGraph: { type: "article", url, title: post.title, description: post.description, siteName: "People Compound", section: post.category },
    twitter: { card: "summary_large_image", title: post.title, description: post.description },
  };
}

export function generateStaticParams(){ return Object.keys(posts).map(slug=>({slug})); }

export default async function InsightPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const post=posts[slug];
  if(!post) return <main><section className="pagehero"><div className="container"><div className="kicker">Insights</div><h1>Insight not found.</h1><Link className="btn btn-primary" href="/insights">Back to Insights</Link></div></section></main>;
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:post.title, description:post.description, articleSection:post.category, author:{"@type":"Organization",name:"People Compound"}, publisher:{"@type":"Organization",name:"People Compound"}, mainEntityOfPage:{"@type":"WebPage","@id":`${siteUrl}/insights/${slug}`}, url:`${siteUrl}/insights/${slug}` }) }} /><section className="article-hero"><div className="container article-container"><span className="tag">{post.category}</span><h1>{post.title}</h1><p className="lead">{post.description}</p><div className="insight-meta">{post.read} · People Compound</div></div></section><section className="section"><div className="container article-layout"><article>{post.sections.map((s,i)=><section className="article-section" key={s.heading}><span className="article-num">0{i+1}</span><h2>{s.heading}</h2>{s.body.map(p=><p key={p}>{p}</p>)}</section>)}</article><aside className="article-aside"><div className="card"><div className="kicker">Put it into practice</div><h3>Start with a clearer picture of where you are.</h3><p>Use a free assessment to identify strengths, focus areas and practical next steps.</p><Link className="btn btn-primary" href="/assessments">Take an assessment</Link></div><div className="card"><div className="kicker">Need a thought partner?</div><h3>Talk through the challenge.</h3><p>People Compound can shape the engagement around the outcome you need.</p><Link className="btn btn-outline" href="/contact">Book a Conversation</Link></div></aside></div></section><section className="section section-sage"><div className="container"><Link className="text-link" href="/insights">← Back to all Insights</Link></div></section></main>;
}
