"use client";
import {useEffect,useMemo,useState} from "react";
import {leadership360Questions} from "../../../../../lib/360";
const scale=["Rarely","Sometimes","Often","Consistently","Very consistently"];
export default function ReviewPage(){
 const [meta,setMeta]=useState<any>(null),[answers,setAnswers]=useState<number[]>(Array(18).fill(0)),[name,setName]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const token=useMemo(()=>typeof window!=="undefined"?new URLSearchParams(window.location.search).get("token")||"":"",[]);
 useEffect(()=>{if(!token)return;fetch(`/api/360/review?token=${encodeURIComponent(token)}`).then(r=>r.json()).then(j=>j.error?setError(j.error):setMeta(j)).catch(()=>setError("We couldn't load this review."))},[token]);
 const progress=answers.filter(Boolean).length;
 if(error)return <main><section className="pagehero"><div className="container"><div className="kicker">360 Leadership Review</div><h1>This review link isn't available.</h1><p className="lead">{error}</p></div></section></main>;
 if(!meta)return <main><section className="pagehero"><div className="container"><div className="kicker">360 Leadership Review</div><h1>Loading your review…</h1></div></section></main>;
 if(meta.completed)return <main><section className="pagehero"><div className="container"><div className="kicker">360 Leadership Review</div><h1>Thank you. Your review has already been submitted.</h1><p className="lead">Your feedback is now part of the People Compound 360 review process.</p></div></section></main>;
 return <main><section className="pagehero"><div className="container"><div className="kicker">People Compound · 360 Leadership Review</div><h1>Help us understand how {meta.participantName} leads.</h1><p className="lead">You were invited by {meta.inviterName} to provide behavior-based feedback. Please answer based on what you have observed, not what you think the person should do.</p><div className="assessment-start-meta"><b>18 questions</b><b>5–7 minutes</b><b>1–5 scale</b><b>Your responses are confidential</b></div></div></section><section className="section"><div className="container assessment-shell"><div className="card" style={{marginBottom:20,background:"var(--sage)"}}><strong>Your perspective matters.</strong><p style={{marginBottom:0}}>There are no right or wrong answers. Use the full scale where appropriate and answer from observed behavior.</p></div><div className="assessment-progress"><span>{progress} of 18 answered</span><span>{Math.round(progress/18*100)}%</span></div>{leadership360Questions.map((q,i)=><div className="question card" key={i}><div className="question-num">{String(i+1).padStart(2,"0")}</div><div><div className="tag">{q[0]}</div><h3>{q[1]}</h3><div className="scale">{scale.map((s,j)=><button type="button" key={s} className={answers[i]===j+1?"selected":""} onClick={()=>setAnswers(v=>{const n=[...v];n[i]=j+1;return n})}><strong>{j+1}</strong><span>{s}</span></button>)}</div></div></div>)}<div className="card" style={{marginTop:20}}><label>Your name<br/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><p className="small-note">Your name is recorded with the review for accountability. Your individual ratings are combined into the integrated report.</p><button className="btn btn-primary" disabled={busy||progress<18||!name.trim()} onClick={async()=>{setBusy(true);setMessage("");setError("");try{const r=await fetch("/api/360/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,reviewerName:name,answers})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Please try again.");setMessage(j.reportDelivery==="sent"?"Thank you. All invited reviewers have completed the review and the integrated report has been sent to the participant.":j.reportDelivery==="waiting"?`Thank you. Your review is recorded. ${j.completed} of ${j.total} invited reviewers have completed the review.`:"Thank you. Your review is recorded.");}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{busy?"Submitting…":"Submit my 360 review →"}</button>{message&&<div className="notice" style={{marginTop:15}}>{message}</div>}{error&&<div className="notice notice-error" style={{marginTop:15}}>{error}</div>}</div></div></section></main>
}
